[book]
authors = ["Rojesh M. Shikhrakar"]
language = "en"
multilingual = false
src = "src"
title = "Getting-Rusty"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2